version: '3.8'

volumes:
  puppet_client_data:


networks:
  puppet-agent-network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24



services:
  puppetclient_one:
    image: puppetclient-one-image
    container_name: puppetclient1
    privileged: true
    build:
      context: .
      dockerfile: puppet_client_one.Dockerfile

    hostname: puppetclient1

    volumes:
      - puppet_client_data:/data/puppetclientone

    networks:
      puppet-agent-network:
        ipv4_address: 192.168.100.3

    extra_hosts:
      - "sddo-vm.localdomain:172.20.113.42"
      - "puppetclient1.localdomain puppetclient1:192.168.100.3"

    # Overrides default command so things don't shut down after the process ends.
    # https://stackoverflow.com/questions/69052575/how-to-bring-up-a-docker-compose-container-as-privileged 
    command: /sbin/init

  puppetclient_two:
    image: puppetclient-two-image
    container_name: puppetclient2
    privileged: true
    build:
      context: .
      dockerfile: puppet_client_two.Dockerfile

    hostname: puppetclient2

    volumes:
      - puppet_client_data:/data/puppetclienttwo

    networks:
      puppet-agent-network:
        ipv4_address: 192.168.100.4

    extra_hosts:
      - "sddo-vm.localdomain:172.20.113.42"
      - "puppetclient2.localdomain puppetclient2:192.168.100.4"

    # Overrides default command so things don't shut down after the process ends.
    # https://stackoverflow.com/questions/69052575/how-to-bring-up-a-docker-compose-container-as-privileged 
    command: /sbin/init