version: '3.8'

volumes:
  portainer_data:

services:
  app:
    image: portainer/portainer-ce:latest
    container_name: portainer-container
    ports:
      - 8000:8000
      - 9000:9000
    build: 
      context: .
    
    volumes:
      - ../..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      
    # Overrides default command so things don't shut down after the process ends.
    
