version: '3.8'

volumes:
  ubuntu_data:

networks:
  puppet-agent-network:
    ipam:
      driver: default
      config:
        - subnet: 172.18.110.0/24

services:
  app:
    image: ubuntu_image
    container_name: pa3114394F
    build:
      context: .
      dockerfile: Dockerfile

    hostname: puppetclient

    volumes:
      - ubuntu_data:/data

    networks:
      puppet-agent-network:
        ipv4_address: 172.18.110.20

    extra_hosts:

      - "puppetmaster puppet:172.20.113.18"

    # Overrides default command so things don't shut down after the process ends.
    command: apachectl -D FOREGROUND
